# Generated by Django 5.0.1 on 2025-11-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteDinamico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_original', models.TextField(help_text='El texto del comando o prompt original enviado por el usuario.')),
                ('consulta_resultante', models.TextField(help_text='La consulta SQL o representación de la consulta ORM resultante.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
