# Generated by Django 5.0.1 on 2025-11-01 20:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_atributoproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_estimators', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
                ('date_range_start', models.DateField()),
                ('date_range_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_training_datetime', models.DateTimeField(auto_now=True)),
                ('rmse', models.FloatField()),
                ('mae', models.FloatField()),
                ('r2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
