# Generated by Django 5.0.1 on 2025-10-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posventa', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warranty',
            name='resolution_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('RESOLVED', 'Resuelto'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=10),
        ),
    ]
