# Generated by Django 5.0.1 on 2025-10-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('PAYPAL', 'PayPal'), ('STRIPE', 'Stripe')], default='PAYPAL', max_length=10),
        ),
    ]
